Pandas project Batch 89/Sowmya G

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np

In [ ]:
title_data = pd.read_csv("C:\\Users\\ADMIN\\Documents\\cast.csv")
title_data.head()

In [23]:
print(title_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3611212 entries, 0 to 3611211
Data columns (total 6 columns):
 #   Column     Dtype  
---  ------     -----  
 0   title      object 
 1   year       int64  
 2   name       object 
 3   type       object 
 4   character  object 
 5   n          float64
dtypes: float64(1), int64(1), object(4)
memory usage: 165.3+ MB
None


In [25]:
#To create a copy of data
Movie_title=title_data.copy()

In [26]:
Movie_title  

title  year                         name  \
0                          Closet Monster  2015                     Buffy #1   
1                         Suuri illusioni  1985                       Homo $   
2                     Battle of the Sexes  2017                      $hutter   
3                    Secret in Their Eyes  2015                      $hutter   
4                              Steve Jobs  2015                      $hutter   
...                                   ...   ...                          ...   
3611207                           Foxtrot  1988            Lilja ??risd?ttir   
3611208  Niceland (Population. 1.000.002)  2004    Sigr??ur J?na ??risd?ttir   
3611209                         Skammdegi  1985           Dalla ??r?ard?ttir   
3611210                      U.S.S.S.S...  2003  Krist?n Andrea ??r?ard?ttir   
3611211                 Bye Bye Blue Bird  1999                 Rosa ? R?gvu   

            type                character     n  
0          actor                  Buffy 4   NaN  
1          actor                   Guests  22.0  
2          actor          Bobby Riggs Fan  10.0  
3          actor          2002 Dodger Fan   NaN  
4          actor  1988 Opera House Patron   NaN  
...          ...                      ...   ...  
3611207  actress                     D?ra  24.0  
3611208  actress             Woman in Bus  26.0  
3611209  actress            Hj?krunarkona   9.0  
3611210  actress   Afgr.dama ? bens?nst??  17.0  
3611211  actress        Pensionatv?rtinde   NaN  

[3611212 rows x 6 columns]

In [27]:
#To check for null values
print(Movie_title.isnull().sum())

title              6
year               0
name               0
type               0
character         14
n            1379242
dtype: int64


In [28]:
Movie_title["title"]=Movie_title["title"].fillna(0)
Movie_title["character"]=Movie_title["character"].fillna(0)
Movie_title["n"]=Movie_title["n"].fillna(0)

In [29]:
print(Movie_title.isnull().sum())

title        0
year         0
name         0
type         0
character    0
n            0
dtype: int64


In [30]:
print(Movie_title.dtypes)

title         object
year           int64
name          object
type          object
character     object
n            float64
dtype: object


### How many movies are listed in the titles dataframe?

In [31]:
Movie_title.shape

(3611212, 6)

In [32]:
#3611212 movies are listed in the titles dataframe

### What are the earliest two films listed in the titles dataframe?

In [33]:
Movie_title.year.value_counts()

year
2016    178217
2015    149596
2014    147878
2013    138976
2012    133912
         ...  
1907         5
1909         3
1894         3
1900         2
1905         1
Name: count, Length: 121, dtype: int64

In [34]:
import numpy as np
yeardata=np.array(Movie_title["year"])
yeardata

array([2015, 1985, 2017, ..., 1985, 2003, 1999], dtype=int64)

In [35]:
print(min(yeardata))
#The earliest year movie was casted is 1894

1894


In [36]:
Movie_title[Movie_title['year'] == '1894']

Empty DataFrame
Columns: [title, year, name, type, character, n]
Index: []

In [37]:
Movie_title["year"].unique()

array([2015, 1985, 2017, 2009, 2014, 1998, 2000, 2016, 2010, 1997, 1977,
       2013, 2011, 2007, 1993, 1963, 2001, 2008, 1971, 1978, 1975, 1996,
       2005, 1992, 1995, 2006, 1914, 2002, 1994, 1957, 1960, 1958, 1984,
       2012, 1969, 1976, 1956, 1970, 1953, 1982, 1986, 2003, 1983, 1999,
       1931, 1968, 1987, 1989, 1980, 1988, 2019, 2018, 1950, 1954, 1948,
       1917, 1935, 1932, 1927, 1938, 1942, 1921, 1918, 1944, 1955, 1952,
       1945, 1981, 1939, 1940, 1949, 1947, 1943, 1991, 2004, 1962, 1979,
       1930, 1973, 1961, 1933, 1964, 1990, 1946, 1965, 1923, 1974, 1967,
       1936, 1929, 1972, 1966, 1959, 1926, 1951, 1941, 1937, 1934, 1922,
       1928, 1920, 1919, 1915, 1925, 1916, 1924, 1913, 2020, 1912, 2023,
       1911, 1910, 2022, 1908, 1909, 1906, 2021, 1894, 1905, 1907, 1900],
      dtype=int64)

In [38]:
no1894=np.count_nonzero(yeardata==1894)
print(f"The number of movies made in the year 1894 are {no1894}")

The number of movies made in the year 1894 are 3


In [39]:
early_movie=Movie_title[Movie_title['year']=='1894']
print(early_movie)

Empty DataFrame
Columns: [title, year, name, type, character, n]
Index: []


### How many movies have the title "Hamlet"?

In [40]:
count_Hamlet=Movie_title.applymap(lambda x:x=="Hamlet").sum().sum()
print(f"{count_Hamlet} movies have the title 'Hamlet'.")

405 movies have the title 'Hamlet'.


### How many movies are titled "North by Northwest"?

In [41]:
Count_North_by_Northwest=Movie_title.applymap(lambda x:x=="North by Northwest").sum().sum()
print(f"{Count_North_by_Northwest} movies have the title 'North by Northwest'.")

112 movies have the title 'North by Northwest'.


### When was the first movie titled "Hamlet" made?

In [42]:
first_H=Movie_title.applymap(lambda x:x=="Hamlet")
first_index=first_H.apply(np.argmax,axis=0)
first_occur_row=Movie_title.loc[first_index]
print(first_occur_row)
##The movie titled 'Hamlet'  was made in the year 1996

                 title  year          name   type              character     n
1615            Hamlet  1996    Riz Abbasi  actor  Attendant to Claudius   1.0
0       Closet Monster  2015      Buffy #1  actor                Buffy 4   0.0
897089          Ritual  2002        Hamlet  actor                 Priest  21.0
0       Closet Monster  2015      Buffy #1  actor                Buffy 4   0.0
6003             Sugar  2008  Hamlet Abreu  actor                 Hamlet  58.0
0       Closet Monster  2015      Buffy #1  actor                Buffy 4   0.0


In [43]:
#checking if Hamlet is present in the location 1615
Movie_title.iloc[[1615,1]]

title  year        name   type              character     n
1615           Hamlet  1996  Riz Abbasi  actor  Attendant to Claudius   1.0
1     Suuri illusioni  1985      Homo $  actor                 Guests  22.0

### List all of the "Treasure Island" movies from earliest to most recent.

In [44]:
Movie_title[Movie_title['title'].isin(['Treasure Island'])]

title  year                 name     type  \
9432     Treasure Island  1934         Robert Adair    actor   
13253    Treasure Island  1950         Chris Adcock    actor   
16246    Treasure Island  1985          Yves Afonso    actor   
42039    Treasure Island  1972   Cristino Almod?var    actor   
55071    Treasure Island  1934  John (XII) Anderson    actor   
...                  ...   ...                  ...      ...   
3415912  Treasure Island  1999        Rachel Singer  actress   
3471316  Treasure Island  1934          Jane Talent  actress   
3507587  Treasure Island  1999     Guinevere Turner  actress   
3553298  Treasure Island  1918   Eleanor Washington  actress   
3556764  Treasure Island  1973            Jane Webb  actress   

                          character     n  
9432                   Tom - Seaman   0.0  
13253                          Pike  26.0  
16246                French captain   8.0  
42039                       O'Brien  16.0  
55071    Pirate of the Spanish Main  18.0  
...                             ...   ...  
3415912                        Anna   6.0  
3471316                Streetwalker   0.0  
3507587                      Evelyn  14.0  
3553298             Prologue Player   0.0  
3556764                Mrs. Hawkins   6.0  

[190 rows x 6 columns]

### How many movies were made in the year 1950?

In [45]:
print(yeardata)
print(len(yeardata))
no1950=np.count_nonzero(yeardata==1950)
print(f"The number of movies made in the year 1950 are {no1950}")

[2015 1985 2017 ... 1985 2003 1999]
3611212
The number of movies made in the year 1950 are 22006


### How many movies were made in the year 1960?

In [46]:
no1960=np.count_nonzero(yeardata==1960)
print(f"The number of movies made in the year 1960 are {no1960}.")

The number of movies made in the year 1960 are 18456.


### How many movies were made from 1950 through 1959?

In [47]:
list1=[]
for y in range(len(yeardata)):
    if y<1960 and y>1949:
        list1=np.append(y,list1)
print(list1)        
l=len(list1)
print(f"The number of movies made from 1950 through 1959 are {l}.")

[1959. 1958. 1957. 1956. 1955. 1954. 1953. 1952. 1951. 1950.]
The number of movies made from 1950 through 1959 are 10.


### In what years has a movie titled "Batman" been released?

In [48]:
Batman_year=Movie_title.applymap(lambda x:x=="Batman")
first_bat=Batman_year.apply(np.argmax,axis=0)
first_bat_row=Movie_title.loc[first_bat]
print(first_bat_row)

##Batman movie was first released in the year 1943

                       title  year          name   type    character    n
95672                 Batman  1943  Frank Austin  actor  Hotel Clerk  0.0
0             Closet Monster  2015      Buffy #1  actor      Buffy 4  0.0
0             Closet Monster  2015      Buffy #1  actor      Buffy 4  0.0
0             Closet Monster  2015      Buffy #1  actor      Buffy 4  0.0
1026   Batman Fights Dracula  1967   Jing Abalos  actor       Batman  1.0
0             Closet Monster  2015      Buffy #1  actor      Buffy 4  0.0


### How many roles were there in the movie "Inception"?

In [49]:
Incept_role=Movie_title.applymap(lambda x:x=="Inception")
Incept_index=Incept_role.apply(np.argmax,axis=0)
Incept=Movie_title.loc[Incept_index]
print(Incept)

##Number of characters in the movie inception  is 1. 

                title  year                  name   type      character    n
94333       Inception  2010  Michael (III) August  actor  LAX Passenger  0.0
0      Closet Monster  2015              Buffy #1  actor        Buffy 4  0.0
0      Closet Monster  2015              Buffy #1  actor        Buffy 4  0.0
0      Closet Monster  2015              Buffy #1  actor        Buffy 4  0.0
0      Closet Monster  2015              Buffy #1  actor        Buffy 4  0.0
0      Closet Monster  2015              Buffy #1  actor        Buffy 4  0.0


In [50]:
#checking if it is in the location
Movie_title.iloc[94333]

title                   Inception
year                         2010
name         Michael (III) August
type                        actor
character           LAX Passenger
n                             0.0
Name: 94333, dtype: object

### How many roles in the movie "Inception" are NOT ranked by an "n" value?

In [51]:
Incept_data=Movie_title[Movie_title['title'].isin(['Inception'])]
print(Incept_data)

             title  year                  name     type  \
94333    Inception  2010  Michael (III) August    actor   
143138   Inception  2010          Peter Basham    actor   
176819   Inception  2010          Tom Berenger    actor   
190249   Inception  2010              Ken Bhan    actor   
250191   Inception  2010        Virgile Bramly    actor   
...            ...   ...                   ...      ...   
3238950  Inception  2010            Ellen Page  actress   
3292669  Inception  2010        Nicole Pulliam  actress   
3319073  Inception  2010    Lisa (II) Reynolds  actress   
3325768  Inception  2010         Talulah Riley  actress   
3560127  Inception  2010        Shannon Welles  actress   

                     character     n  
94333            LAX Passenger   0.0  
143138   Fischer's Jet Captain  44.0  
176819                Browning   8.0  
190249        Mombasan Gambler   0.0  
250191          Bridge Sub Con  29.0  
...                        ...   ...  
3238950           

In [52]:
n=np.array(Incept_data['n'])
inceptlen=len(n)
print(f"{inceptlen} movies are having the title 'Inception'.")
ncount=np.count_nonzero(n==0.0)   
print(f"{ncount} number of roles are not having the 'n' value")

77 movies are having the title 'Inception'.
26 number of roles are not having the 'n' value


### But how many roles in the movie "Inception" did receive an "n" value?

In [13]:
#It will be 77-26 which is 51.

### Display the cast of "North by Northwest" in their correct "n"-value order, ignoring roles that did not earn a numeric "n" value.

In [53]:
North_by_Northwest=Movie_title[Movie_title['title'].isin(['North by Northwest'])]
print(North_by_Northwest)

                      title  year               name     type  \
12151    North by Northwest  1959      Stanley Adams    actor   
27852    North by Northwest  1959         Andy Albin    actor   
54093    North by Northwest  1959       Don Anderson    actor   
54307    North by Northwest  1959    Ernest Anderson    actor   
92195    North by Northwest  1959  Malcolm Atterbury    actor   
...                     ...   ...                ...      ...   
3361396  North by Northwest  1959    Eva Marie Saint  actress   
3416124  North by Northwest  1959        Doris Singh  actress   
3437248  North by Northwest  1959       Helen Spring  actress   
3567500  North by Northwest  1959      Susan Whitney  actress   
3578877  North by Northwest  1959     Paula Winslowe  actress   

                                 character    n  
12151                   Lieutenant Harding  0.0  
27852                               Farmer  0.0  
54093                               Worker  0.0  
54307     Porter on

### Display the entire cast, in "n"-order, of the 1972 film "Sleuth".

In [54]:
#Convert n into an array
NbN=np.array(North_by_Northwest['n'])
print(NbN)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 15.  0.  5.  0.  0.  0.  0.
 13.  0.  0.  0.  0.  0.  0.  0. 11.  0.  0.  0.  0.  0.  1.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  8.  0.  0.  0. 16.  0.  0.  0.
  3.  0. 14.  0.  0.  0.  0.  0.  7. 10.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 12.  0.  0.  0.  9.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  6.  0.  4.  0.  0.  0.  0.  2.
  0.  0.  0.  0.]


In [55]:
NN=[]
for i in range(len(NbN)):
    if NbN[i]>0:
        NN=np.append(NbN[i],NN)
lenNN=len(NN)        
print(f"The number of movies having 'n' values are {lenNN}")        
print(NN)

The number of movies having 'n' values are 16
[ 2.  4.  6.  9. 12. 10.  7. 14.  3. 16.  8.  1. 11. 13.  5. 15.]


In [56]:
loc=North_by_Northwest[North_by_Northwest==1].stack().index.tolist()
print(loc)

[(840374, 'n')]


In [57]:
North_by_Northwest.loc[840374]

title        North by Northwest
year                       1959
name                 Cary Grant
type                      actor
character    Roger O. Thornhill
n                           1.0
Name: 840374, dtype: object

### Now display the entire cast, in "n"-order, of the 2007 version of "Sleuth".

In [58]:
Sleuth_data=Movie_title[Movie_title['character'].isin(['Sleuth'])]
print(Sleuth_data)

                                    title  year                  name   type  \
665149   C.O.O.L.I.O Time Travel Gangster  2014     Nathan (XV) Evans  actor   
1164226                          Zeta One  1969           Steve Kirby  actor   
1363119             Andzamb tchanachum em  1958              P. Malek  actor   
1654211                  Darmozjad polski  1998  Slawomir Orzechowski  actor   
1865676                   American Yakuza  1993         Scott Roberts  actor   
1865679                       No Way Back  1995         Scott Roberts  actor   
2424344                    Przyspieszenie  1985      Andrzej Zarnecki  actor   

        character     n  
665149     Sleuth   0.0  
1164226    Sleuth  13.0  
1363119    Sleuth  17.0  
1654211    Sleuth   8.0  
1865676    Sleuth   0.0  
1865679    Sleuth   0.0  
2424344    Sleuth   0.0  


In [59]:
Sleuth_data.shape

(7, 6)

### How many roles were credited in the silent 1921 version of Hamlet?

### How many roles were credited in Branagh’s 1996 Hamlet?

In [61]:
Bran_Ham_role=Movie_title[Movie_title['character'].isin(['Branagh'])]
print(Bran_Ham_role)


Empty DataFrame
Columns: [title, year, name, type, character, n]
Index: []


### How many "Hamlet" roles have been listed in all film credits through history?

In [62]:
Ham_role=Movie_title[Movie_title['character'].isin(['Hamlet'])]
print(Ham_role)


                                 title  year               name     type  \
6003                             Sugar  2008       Hamlet Abreu    actor   
94018                  Top of the Town  1937        Mischa Auer    actor   
120093             The Sound of Spying  2014      Jonathan Ball    actor   
154451                Suivez cet avion  1989  Fran?ois Beaulieu    actor   
154754          Nous sommes les autres  2017       Marc Beaupr?    actor   
...                                ...   ...                ...      ...   
2517189                       Hamlet_X  2003       Meret Becker  actress   
2622924  Bill Shakespeare in Hollywood  2011    Rafika Chawishe  actress   
2825750    Intikam Melegi/Kadin Hamlet  1976        Fatma Girik  actress   
3209199                         Hamlet  1921       Asta Nielsen  actress   
3256505                         Hamlet  2015       Maxine Peake  actress   

        character     n  
6003       Hamlet  58.0  
94018      Hamlet   6.0  
120093   

In [ ]:
# 91 Hamlet roles have been listed through the history.

### How many people have played an "Ophelia"?

In [63]:
Opel=Movie_title[Movie_title['character'].isin(['Ophelia'])]
print(Opel)


                                   title  year                  name     type  \
238855        The Merry Maids of Madness  2016           Amy Bourque    actor   
395196                    Jake Gets Paid  2009        Josie Chisholm    actor   
453835                        Inoperable  2016       Crystal Cordero    actor   
835461   Dogg's Hamlet, Cahoot's Macbeth  2005         Lucas Grabeel    actor   
1315145                               11  2014   Catherine (IV) Lord    actor   
...                                  ...   ...                   ...      ...   
3538349         Hamlet, Son of a Kingpin  2015        Ingrid Vollset  actress   
3551691                         D.C. Cab  1983       Marsha Warfield  actress   
3552384                         Creature  2011  Jennifer Lynn Warren  actress   
3562331                           Hamlet  2015       Katie (II) West  actress   
3578802                           Hamlet  1996          Kate Winslet  actress   

        character     n  
2

In [ ]:
# 111 people have played the Ophelia.

### How many people have played a role called "The Dude"?

In [64]:
TheDude=Movie_title[Movie_title['character'].isin(['The Dude'])]
print(TheDude)


                                  title  year                  name   type  \
261792                 The Big Lebowski  1998          Jeff Bridges  actor   
326893               Terms & Conditions  2015           Jordan Cann  actor   
480810                         Stranger  2000         Scott Crowell  actor   
549887           Pizza Man vs. the Dude  2004        Chris DeMarcus  actor   
588962                      Sweepstakes  1931           Mike Donlin  actor   
607151                    Self Helpless  2010        Devin The Dude  actor   
1051244  Jay and Silent Bob Strike Back  2001   Matthew (XIX) James  actor   
1098711                   Explicit Ills  2008    Christopher Kadish  actor   
1317786                 American Idiots  2013      Jason Loughridge  actor   
1336484             The Winds of Autumn  1976           Steve Lyons  actor   
1458465                         The Liq  2016        Mark Alan Meek  actor   
1485772                  Wild Oats Lane  1926           Jerry Mi

In [65]:
TheDude.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 261792 to 2330925
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   title      18 non-null     object 
 1   year       18 non-null     int64  
 2   name       18 non-null     object 
 3   type       18 non-null     object 
 4   character  18 non-null     object 
 5   n          18 non-null     float64
dtypes: float64(1), int64(1), object(4)
memory usage: 1008.0+ bytes


In [ ]:
#The number of people that played the role 'The Dude' are 18

### How many people have played a role called "The Stranger"?

In [66]:
Stranger=Movie_title[Movie_title['character'].isin(['The Stranger'])]
print(Stranger)


                            title  year                       name     type  \
24819                       Theeb  2014  Hassan Mutlag Al-Maraiyeh    actor   
34302              My Time to Die  2014       Vincent H. Alexander    actor   
64774                    Get Mean  1975               Tony Anthony    actor   
64777    Lo straniero di silenzio  1968               Tony Anthony    actor   
64779      Un dollaro tra i denti  1967               Tony Anthony    actor   
...                           ...   ...                        ...      ...   
3068419              The Stranger  1995                 Kathy Long  actress   
3081837            Ever Since Eve  1921                Ethel Lynne  actress   
3256243              Weitertanzen  2008             Rosa Maria Paz  actress   
3276867               The Godsend  1980           Angela Pleasence  actress   
3407234                Motherland  1927            Dorinea Shirley  actress   

            character    n  
24819    The Stranger 

In [ ]:
#Number of people have played the role 'The Stranger' are 208

### How many roles has Sidney Poitier played throughout his career?

In [67]:
SPoitier=Movie_title[Movie_title['name'].isin(['Sidney Poitier'])]
print(SPoitier)


                                title  year            name   type  \
1751059               A Patch of Blue  1965  Sidney Poitier  actor   
1751060         A Piece of the Action  1977  Sidney Poitier  actor   
1751061           A Raisin in the Sun  1961  Sidney Poitier  actor   
1751062               A Warm December  1973  Sidney Poitier  actor   
1751063             All the Young Men  1960  Sidney Poitier  actor   
1751064                Band of Angels  1957  Sidney Poitier  actor   
1751065             Blackboard Jungle  1955  Sidney Poitier  actor   
1751066                  Brother John  1971  Sidney Poitier  actor   
1751067         Buck and the Preacher  1972  Sidney Poitier  actor   
1751068      Cry, the Beloved Country  1951  Sidney Poitier  actor   
1751069                Duel at Diablo  1966  Sidney Poitier  actor   
1751070              Edge of the City  1957  Sidney Poitier  actor   
1751071               For Love of Ivy  1968  Sidney Poitier  actor   
1751072             

In [68]:
SPoitier.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43 entries, 1751059 to 1751101
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   title      43 non-null     object 
 1   year       43 non-null     int64  
 2   name       43 non-null     object 
 3   type       43 non-null     object 
 4   character  43 non-null     object 
 5   n          43 non-null     float64
dtypes: float64(1), int64(1), object(4)
memory usage: 2.4+ KB


In [ ]:
#Sidney Poitier has played 43 roles throughout his career

### How many roles has Judi Dench played?

In [69]:
Judi=Movie_title[Movie_title['name'].isin(['Judi Dench'])]
print(Judi)


                                                     title  year        name  \
2703455                              84 Charing Cross Road  1987  Judi Dench   
2703456                                  A Handful of Dust  1988  Judi Dench   
2703457                          A Midsummer Night's Dream  1968  Judi Dench   
2703458                                 A Room with a View  1985  Judi Dench   
2703459                                  A Study in Terror  1965  Judi Dench   
2703460             Angelina Ballerina: Angelina Sets Sail  2006  Judi Dench   
2703461                                      Casino Royale  2006  Judi Dench   
2703462                                           Chocolat  2000  Judi Dench   
2703463                                          Dead Cert  1974  Judi Dench   
2703464                                    Die Another Day  2002  Judi Dench   
2703465                                             Doogal  2006  Judi Dench   
2703466                                F

In [70]:
Judi.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55 entries, 2703455 to 2703509
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   title      55 non-null     object 
 1   year       55 non-null     int64  
 2   name       55 non-null     object 
 3   type       55 non-null     object 
 4   character  55 non-null     object 
 5   n          55 non-null     float64
dtypes: float64(1), int64(1), object(4)
memory usage: 3.0+ KB


In [71]:
#Judi Dench has played 55 roles

### List the supporting roles (having n=2) played by Cary Grant in the 1940s, in order by year.

In [72]:
Cary=Movie_title[Movie_title['character'].isin(['Cary Grant'])]
print(Cary)

                           title  year                name   type   character  \
330721            Broken Promise  2006       Merrill Capps  actor  Cary Grant   
840351   George White's Scandals  1945          Cary Grant  actor  Cary Grant   
840415      Without Reservations  1946          Cary Grant  actor  Cary Grant   
908803          Received Payment  1922      Kenneth Harlan  actor  Cary Grant   
2177810           Curtsy, Mister  2017   Ashford J. Thomas  actor  Cary Grant   
2381272              The Aviator  2004  Michael-John Wolfe  actor  Cary Grant   

           n  
330721   0.0  
840351   0.0  
840415   0.0  
908803   2.0  
2177810  0.0  
2381272  0.0  


In [74]:
Movie_title.iloc[908803]

title        Received Payment
year                     1922
name           Kenneth Harlan
type                    actor
character          Cary Grant
n                         2.0
Name: 908803, dtype: object

In [ ]:
#Supporting role was done by Kenneth Harlan

### List the leading roles that Cary Grant played in the 1940s in order by year.

In [75]:
Cary=Movie_title[Movie_title['name'].isin(['Cary Grant'])]
print(Cary)

                        title  year        name   type            character  \
840334    Alice in Wonderland  1933  Cary Grant  actor          Mock Turtle   
840335  An Affair to Remember  1957  Cary Grant  actor      Nickie Ferrante   
840336   Arsenic and Old Lace  1944  Cary Grant  actor    Mortimer Brewster   
840337         Big Brown Eyes  1936  Cary Grant  actor           Danny Barr   
840338           Blonde Venus  1932  Cary Grant  actor        Nick Townsend   
...                       ...   ...         ...    ...                  ...   
840411         Walk Don't Run  1966  Cary Grant  actor  Sir William Rutland   
840412        Wedding Present  1936  Cary Grant  actor        Charlie Mason   
840413    When You're in Love  1937  Cary Grant  actor         Jimmy Hudson   
840414      Wings in the Dark  1935  Cary Grant  actor           Ken Gordon   
840415   Without Reservations  1946  Cary Grant  actor           Cary Grant   

           n  
840334  10.0  
840335   1.0  
840336

In [78]:
array_cary=np.array(Cary['year'])             

In [83]:
new_arr=[]
for i in range(len(array_cary)):
    if array_cary[i]<1950 and array_cary[i]>1939:
               new_arr=np.append(array_cary[i],new_arr)

               
print(new_arr)               
cary_len=len(new_arr)              
print(f"The number roles played by Cary in 1940's are:{cary_len} ")                                             

[1946. 1942. 1940. 1940. 1947. 1947. 1941. 1941. 1944. 1942. 1946. 1944.
 1946. 1940. 1943. 1943. 1948. 1949. 1940. 1945. 1948. 1943. 1944.]
The number roles played by Cary in 1940's are:23 


In [84]:
sorted(new_arr)

[1940.0,
 1940.0,
 1940.0,
 1940.0,
 1941.0,
 1941.0,
 1942.0,
 1942.0,
 1943.0,
 1943.0,
 1943.0,
 1944.0,
 1944.0,
 1944.0,
 1945.0,
 1946.0,
 1946.0,
 1946.0,
 1947.0,
 1947.0,
 1948.0,
 1948.0,
 1949.0]

### How many roles were available for actors in the 1950s?

In [85]:
actor=Movie_title[Movie_title['type'].isin(['actor'])]
print(actor)


                                     title  year                     name  \
0                           Closet Monster  2015                 Buffy #1   
1                          Suuri illusioni  1985                   Homo $   
2                      Battle of the Sexes  2017                  $hutter   
3                     Secret in Their Eyes  2015                  $hutter   
4                               Steve Jobs  2015                  $hutter   
...                                    ...   ...                      ...   
2440023                            Rokland  2011     Run?lfur ??rhallsson   
2440024                        Vychislitel  2014  Dav?? Freyr ??runnarson   
2440025                        Gauragangur  2010         Ingvar ??r?arson   
2440026  Reykjavik Whale Watching Massacre  2009         Ingvar ??r?arson   
2440027            The Sleep of Cyma Roget  1920         Legaren ? Hiller   

          type                character     n  
0        actor             

In [86]:
array1950=np.array(actor['year'])
arr1=[]    
for i in range(len(array1950)):
    if array1950[i]==1950:
        arr1=np.append(array1950[i],arr1)
print(arr1)  
print("The number of roles available for actors in 1950 were",len(arr1))
        


[1950. 1950. 1950. ... 1950. 1950. 1950.]
The number of roles available for actors in 1950 were 16512


In [87]:
Movie_title.head(3)

title  year      name   type        character     n
0       Closet Monster  2015  Buffy #1  actor          Buffy 4   0.0
1      Suuri illusioni  1985    Homo $  actor           Guests  22.0
2  Battle of the Sexes  2017   $hutter  actor  Bobby Riggs Fan  10.0

### How many roles were available for actresses in the 1950s?

In [88]:
female=Movie_title.query('type == "actress"')
print(female)


                                                  title  year  \
2440028                             Night of the Demons  2009   
2440029  The Bad Lieutenant: Port of Call - New Orleans  2009   
2440030  The Bad Lieutenant: Port of Call - New Orleans  2009   
2440031                          A Woman of Distinction  1950   
2440032                                Around the World  1943   
...                                                 ...   ...   
3611207                                         Foxtrot  1988   
3611208                Niceland (Population. 1.000.002)  2004   
3611209                                       Skammdegi  1985   
3611210                                    U.S.S.S.S...  2003   
3611211                               Bye Bye Blue Bird  1999   

                                   name     type               character     n  
2440028  Stefanie Oxmann Mcgaha "Steff"  actress              Goth raver   0.0  
2440029  Stefanie Oxmann Mcgaha "Steff"  actress         

In [89]:
arrayfemale=np.array(female['year'])
arr2=[]    
for i in range(len(arrayfemale)):
    if arrayfemale[i]==1950:
        arr2=np.append(arrayfemale[i],arr2)
print(arr2)  
print("The number of roles available for actress in 1950 were",len(arr2))
        


[1950. 1950. 1950. ... 1950. 1950. 1950.]
The number of roles available for actress in 1950 were 5494


### How many leading roles (n=1) were available from the beginning of film history through 1980?

In [90]:
yeardata

array([2015, 1985, 2017, ..., 1985, 2003, 1999], dtype=int64)

In [ ]:
arr1980=[]
for i in range(len(yeardata)):
    if yeardata[i]>=1980 and yeardata[i]<1990:
        arr1980=np.append(yeardata[i],arr1980)
print(arr1980)        
print(len(arr1980))

### How many non-leading roles were available through from the beginning of film history through 1980?

### How many roles through 1980 were minor enough that they did not warrant a numeric "n" rank?